### ISSUE TITLE
System.loadLibrary("Natciml");

### ISSUE THREAD

**Issue by modianor** [sumous/anti_sign#2]
你好，我最近在在逆向variflight的sign，这里明明加载了Natciml这个so库，但是我却找不到这个库文件，请问能指点下吗？[
![image](https://user-images.githubusercontent.com/24886976/97768815-c8867f00-1b60-11eb-8626-26c473f33bb7.png)
](url)

**Comment by sumous** [comment]
lib/armeabi-v7a/libNatciml.so  文件位置。

**Comment by modianor** [comment]
> lib/armeabi-v7a/libNatciml.so  文件位置。
> 
> 

谢谢 我眼睛瞎掉了 我看了好几遍居然没看到🌚🌚
